// RESearch.idl : IDL source for RESearch.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (RESearch.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[	uuid(B6CA758A-78FB-4093-84D3-0A88D8EA7285),
	version(1.0),
	helpstring("RESearch 1.0 Type Library")
]
library RESearchLib
{

[	object,
	uuid(22B6F9B8-CDB4-4cb9-9D5F-F2B36C3F76BC),
	dual,
	helpstring("IReplaceParameters Interface"),
	pointer_default(unique),
	nonextensible
]
interface IReplaceParameters : IDispatch
{
	HRESULT match([in] long lPos, [out,retval] BSTR *pbstrMatch);
	HRESULT named([in] BSTR strParam, [out,retval] BSTR *pbstrMatch);
	HRESULT result([in] BSTR bstrResult);

	HRESULT eol([out,retval] BSTR *pbstrEOL);
	HRESULT l([out,retval] long *pValue);
	HRESULT n([out,retval] long *pValue);
	HRESULT r([out,retval] long *pValue);
};

}
