//#ifndef __PERSISTVARS_H
//#define __PERSISTVARS_H

#ifdef DECLARE_PERSIST_VARS
	#define PERSIST_BOOL_VARIABLE(Name, Default) EXTERN BOOL Name VALUE(Default);
	#define PERSIST_STRING_VARIABLE(Name, Default) EXTERN string Name;
	#define PERSIST_TYPED_VARIABLE(Type, Name, Default, Min, Max) EXTERN Type Name VALUE(Default);
	#define PERSIST_FILETIME_VARIABLE(Name) EXTERN FILETIME Name;
	#undef DECLARE_PERSIST_VARS
#else
#ifdef DECLARE_PERSIST_LOAD
	#define PERSIST_BOOL_VARIABLE(Name, Default) QueryRegIntValue(Key, #Name, &Name, Default, 0, 1);
	#define PERSIST_STRING_VARIABLE(Name, Default) QueryRegStringValue(Key, #Name, Name, Default);
	#define PERSIST_TYPED_VARIABLE(Type, Name, Default, Min, Max) QueryRegIntValue(Key, #Name, (int *)&Name, Default, Min, Max);
	#define PERSIST_FILETIME_VARIABLE(Name) QueryRegIntValue(Key, #Name "Lo", &Name.dwLowDateTime, 0xE1D58000); QueryRegIntValue(Key, #Name "Hi", &Name.dwHighDateTime, 0x01A8E79F);
	#undef DECLARE_PERSIST_LOAD
#else
#ifdef DECLARE_PERSIST_SAVE
	#define PERSIST_BOOL_VARIABLE(Name, Default) SetRegIntValue(Key, #Name, Name);
	#define PERSIST_STRING_VARIABLE(Name, Default) SetRegStringValue(Key, #Name, Name);
	#define PERSIST_TYPED_VARIABLE(Type, Name, Default, Min, Max) SetRegIntValue(Key, #Name, Name);
	#define PERSIST_FILETIME_VARIABLE(Name) SetRegIntValue(Key, #Name "Lo", Name.dwLowDateTime); SetRegIntValue(Key, #Name "Hi", Name.dwHighDateTime);
	#undef DECLARE_PERSIST_SAVE
#else
	#error Don't know what to do
#endif
#endif
#endif

PERSIST_BOOL_VARIABLE(FCaseSensitive, FALSE)
PERSIST_BOOL_VARIABLE(FMaskAsRegExp, FALSE)
//PERSIST_BOOL_VARIABLE(FUTF8, FALSE)
PERSIST_STRING_VARIABLE(FMask, "*.*")
PERSIST_STRING_VARIABLE(FText, "")
PERSIST_TYPED_VARIABLE(SearchAs, FSearchAs, SA_PLAINTEXT, SA_PLAINTEXT, SA_MULTIREGEXP)
PERSIST_TYPED_VARIABLE(SearchIn, FSearchIn, SI_FROMCURRENT, SI_ALLDRIVES, SI_SELECTED)
PERSIST_TYPED_VARIABLE(MaskCase, FMaskCase, MC_VOLUME, MC_SENSITIVE, MC_VOLUME)
PERSIST_TYPED_VARIABLE(eReplaceReadonly, FRReplaceReadonly, RR_ASK, RR_NEVER, RR_ALWAYS)

PERSIST_BOOL_VARIABLE(FSInverse, FALSE)
PERSIST_BOOL_VARIABLE(FAllCharTables, FALSE)
PERSIST_STRING_VARIABLE(FRReplace, "")
PERSIST_BOOL_VARIABLE(FROpenModified, FALSE)
PERSIST_BOOL_VARIABLE(FRConfirmFile, TRUE)
PERSIST_BOOL_VARIABLE(FRConfirmLine, TRUE)
PERSIST_BOOL_VARIABLE(FRSaveOriginal, FALSE)
PERSIST_BOOL_VARIABLE(FROverwriteBackup, TRUE)
PERSIST_BOOL_VARIABLE(FRepeating, FALSE)

PERSIST_BOOL_VARIABLE(FACaseSensitive, FALSE)
PERSIST_BOOL_VARIABLE(FADirectoryCaseSensitive, FALSE)
PERSIST_BOOL_VARIABLE(FAFullFileNameMatch, FALSE)
PERSIST_BOOL_VARIABLE(FAFullFileNameInverse, FALSE)
PERSIST_STRING_VARIABLE(FAFullFileName, "")

PERSIST_BOOL_VARIABLE(FADirectoryMatch, FALSE)
PERSIST_BOOL_VARIABLE(FADirectoryInverse, FALSE)
PERSIST_STRING_VARIABLE(FADirectoryName, "")
PERSIST_TYPED_VARIABLE(DWORD, FARecursionLevel, 0, 0, 256)
PERSIST_BOOL_VARIABLE(FASkipSystemFolders, FALSE)
PERSIST_STRING_VARIABLE(FASystemFolders, "CVS.;.svn;_svn.")

PERSIST_BOOL_VARIABLE(FADateBefore, FALSE)
PERSIST_FILETIME_VARIABLE(FADateBeforeThis)
PERSIST_BOOL_VARIABLE(FADateAfter, FALSE)
PERSIST_FILETIME_VARIABLE(FADateAfterThis)
PERSIST_BOOL_VARIABLE(FAModificationDate, FALSE)

PERSIST_BOOL_VARIABLE(FASizeLess, FALSE)
PERSIST_TYPED_VARIABLE(DWORD, FASizeLessLimit, 0, 0, 0x7FFFFFFF)
PERSIST_BOOL_VARIABLE(FASizeGreater, FALSE)
PERSIST_TYPED_VARIABLE(DWORD, FASizeGreaterLimit, 0, 0, 0x7FFFFFFF)

PERSIST_TYPED_VARIABLE(DWORD, FAAttributesSet, 0, 0, 0x7FFFFFFF)
PERSIST_TYPED_VARIABLE(DWORD, FAAttributesCleared, 0, 0, 0x7FFFFFFF)

PERSIST_BOOL_VARIABLE(FASearchHead, FALSE)
PERSIST_TYPED_VARIABLE(DWORD, FASearchHeadLimit, 0, 0, 0x7FFFFFFF)


#undef PERSIST_BOOL_VARIABLE
#undef PERSIST_STRING_VARIABLE
#undef PERSIST_TYPED_VARIABLE
#undef PERSIST_FILETIME_VARIABLE

//#endif
