#include <PersistVariables.h>

PERSIST_STRING_VARIABLE(EText, "")
PERSIST_STRING_VARIABLE(ERReplace, "")
PERSIST_BOOL_VARIABLE(ERegExp, FALSE)
PERSIST_BOOL_VARIABLE(ESeveralLine, FALSE)
PERSIST_BOOL_VARIABLE(ECaseSensitive, FALSE)

PERSIST_TYPED_VARIABLE(int, EREvaluateScript, 0, 0, 255)

PERSIST_BOOL_VARIABLE(EFLeaveFilter, TRUE)

PERSIST_STRING_VARIABLE(ETSource, "")
PERSIST_STRING_VARIABLE(ETTarget, "")

#include <PersistVariablesUndef.h>
